const pageDetailsTypes = {
  SET_CURRENT_PAGE_DETAILS: "SET_CURRENT_PAGE_DETAILS",
  SET_CURRENT_PATH_ARRAY: "SET_CURRENT_PATH_ARRAY",
  SET_CURRENT_RECIPE: "SET_CURRENT_RECIPE",
  UPDATE_CURRENT_RECIPE: "UPDATE_CURRENT_RECIPE",
};

export default pageDetailsTypes;
