const recipesTypes = {
  DEFAULT_RECIPES_START: "DEFAULT_RECIPES_START",
  SET_RECIPES: "SET_RECIPES",
  DEFAULT_SPECIALS_START: "DEFAULT_SPECIALS_START",
  SET_SPECIALS: "SET_SPECIALS",
  API_LOADED: "API_LOADED",
};

export default recipesTypes;
