const locationsTypes = {
  SET_LOCATION_ADDRESS_START: "SET_LOCATION_ADDRESS_START",
  SET_LOCATION_ADDRESS: "SET_LOCATION_ADDRESS",
  SET_LOCATION_LAT_LNG: "SET_LOCATION_LAT_LNG",
};

export default locationsTypes;
